### ISSUE TITLE
Please Update

### ISSUE THREAD

**Issue by ardwk** [Focuslinkstech/phpnuxbill-router-monitor-plugin#1]
<img width="1036" alt="Screen Shot 2024-05-17 at 21 07 57" src="https://github.com/Focuslinkstech/phpnuxbill-router-monitor-plugin/assets/65375511/8126c4eb-2f46-4212-82c9-3ca53b5bbe2a">

**Comment by Focuslinkstech** [comment]
what is the issue?

**Comment by ardwk** [comment]
RX and TX on PPPOE data does not appear

**Comment by Focuslinkstech** [comment]
Its only available in the pro version
